/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SplitSheetRouteImport } from './routes/split-sheet'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedMyBeatsRouteImport } from './routes/_authenticated/my-beats'
import { Route as BeatsIndexRouteImport } from './routes/beats.index'
import { Route as BeatsSlugRouteImport } from './routes/beats.$slug'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as LicencesIndexRouteImport } from './routes/licences.index'
import { Route as LicencesExclusiveRouteImport } from './routes/licences.exclusive'
import { Route as LicencesUnlimitedLeaseRouteImport } from './routes/licences.unlimited-lease'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitSheetRoute = SplitSheetRouteImport.update({
  id: '/split-sheet',
  path: '/split-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyBeatsRoute = AuthenticatedMyBeatsRouteImport.update({
  id: '/my-beats',
  path: '/my-beats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BeatsIndexRoute = BeatsIndexRouteImport.update({
  id: '/beats/',
  path: '/beats/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeatsSlugRoute = BeatsSlugRouteImport.update({
  id: '/beats/$slug',
  path: '/beats/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LicencesIndexRoute = LicencesIndexRouteImport.update({
  id: '/licences/',
  path: '/licences/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicencesExclusiveRoute = LicencesExclusiveRouteImport.update({
  id: '/licences/exclusive',
  path: '/licences/exclusive',
  getParentRoute: () => rootRouteImport,
} as any)
const LicencesUnlimitedLeaseRoute = LicencesUnlimitedLeaseRouteImport.update({
  id: '/licences/unlimited-lease',
  path: '/licences/unlimited-lease',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/split-sheet': typeof SplitSheetRoute
  '/terms': typeof TermsRoute
  '/my-beats': typeof AuthenticatedMyBeatsRoute
  '/beats/$slug': typeof BeatsSlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/licences/exclusive': typeof LicencesExclusiveRoute
  '/licences/unlimited-lease': typeof LicencesUnlimitedLeaseRoute
  '/beats/': typeof BeatsIndexRoute
  '/licences/': typeof LicencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/split-sheet': typeof SplitSheetRoute
  '/terms': typeof TermsRoute
  '/my-beats': typeof AuthenticatedMyBeatsRoute
  '/beats/$slug': typeof BeatsSlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/licences/exclusive': typeof LicencesExclusiveRoute
  '/licences/unlimited-lease': typeof LicencesUnlimitedLeaseRoute
  '/beats': typeof BeatsIndexRoute
  '/licences': typeof LicencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/split-sheet': typeof SplitSheetRoute
  '/terms': typeof TermsRoute
  '/_authenticated/my-beats': typeof AuthenticatedMyBeatsRoute
  '/beats/$slug': typeof BeatsSlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/licences/exclusive': typeof LicencesExclusiveRoute
  '/licences/unlimited-lease': typeof LicencesUnlimitedLeaseRoute
  '/beats/': typeof BeatsIndexRoute
  '/licences/': typeof LicencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/split-sheet'
    | '/terms'
    | '/my-beats'
    | '/beats/$slug'
    | '/checkout/$slug'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/licences/exclusive'
    | '/licences/unlimited-lease'
    | '/beats/'
    | '/licences/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/split-sheet'
    | '/terms'
    | '/my-beats'
    | '/beats/$slug'
    | '/checkout/$slug'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/licences/exclusive'
    | '/licences/unlimited-lease'
    | '/beats'
    | '/licences'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/split-sheet'
    | '/terms'
    | '/_authenticated/my-beats'
    | '/beats/$slug'
    | '/checkout/$slug'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/licences/exclusive'
    | '/licences/unlimited-lease'
    | '/beats/'
    | '/licences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  SplitSheetRoute: typeof SplitSheetRoute
  TermsRoute: typeof TermsRoute
  BeatsSlugRoute: typeof BeatsSlugRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  LicencesExclusiveRoute: typeof LicencesExclusiveRoute
  LicencesUnlimitedLeaseRoute: typeof LicencesUnlimitedLeaseRoute
  BeatsIndexRoute: typeof BeatsIndexRoute
  LicencesIndexRoute: typeof LicencesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-sheet': {
      id: '/split-sheet'
      path: '/split-sheet'
      fullPath: '/split-sheet'
      preLoaderRoute: typeof SplitSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-beats': {
      id: '/_authenticated/my-beats'
      path: '/my-beats'
      fullPath: '/my-beats'
      preLoaderRoute: typeof AuthenticatedMyBeatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/beats/': {
      id: '/beats/'
      path: '/beats'
      fullPath: '/beats/'
      preLoaderRoute: typeof BeatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beats/$slug': {
      id: '/beats/$slug'
      path: '/beats/$slug'
      fullPath: '/beats/$slug'
      preLoaderRoute: typeof BeatsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licences/': {
      id: '/licences/'
      path: '/licences'
      fullPath: '/licences/'
      preLoaderRoute: typeof LicencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licences/exclusive': {
      id: '/licences/exclusive'
      path: '/licences/exclusive'
      fullPath: '/licences/exclusive'
      preLoaderRoute: typeof LicencesExclusiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licences/unlimited-lease': {
      id: '/licences/unlimited-lease'
      path: '/licences/unlimited-lease'
      fullPath: '/licences/unlimited-lease'
      preLoaderRoute: typeof LicencesUnlimitedLeaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMyBeatsRoute: typeof AuthenticatedMyBeatsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMyBeatsRoute: AuthenticatedMyBeatsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  SplitSheetRoute: SplitSheetRoute,
  TermsRoute: TermsRoute,
  BeatsSlugRoute: BeatsSlugRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  LicencesExclusiveRoute: LicencesExclusiveRoute,
  LicencesUnlimitedLeaseRoute: LicencesUnlimitedLeaseRoute,
  BeatsIndexRoute: BeatsIndexRoute,
  LicencesIndexRoute: LicencesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
